Repository pharapeti/group-arrangement, pull requests merged in 2021-04, with the labels that each got.

#3 Database migrations
  README.md
  config/config.json
  database.json
  db/group_arrangement_development.db
  migrations/20210325122734-AddProject.js
  migrations/20210330120701-create-user.js
  migrations/20210330122257-create-project.js
  migrations/20210330123431-create-group.js
  migrations/20210330124350-create-group-allocation.js
  migrations/20210330124539-create-preference-category.js
  migrations/20210330124734-create-project-requirement.js
  migrations/20210330125007-create-preference.js
  migrations/20210330125235-create-preference-selection.js
  models/group.js
  models/groupallocation.js
  models/index.js
  models/preference.js
  models/preferencecategory.js
  models/preferenceselection.js
  models/project.js
  models/projectrequirement.js
  models/user.js
  package-lock.json
  package.json
  scripts/database_setup.sh
  server.js
Labels: review please

#4 Add Model Associations
  models/group.js
  models/groupallocation.js
  models/preference.js
  models/preferencecategory.js
  models/preferenceselection.js
  models/project.js
  models/projectrequirement.js
  models/user.js
Labels: review please

#6 US1: Backend - Implement simple user authentication
  controllers/users/projects/projects.controller.js
  controllers/users/users.controller.js
  middleware/auth.js
  package.json
  routes/user.routes.js
  routes/users/projects/project.routes.js
  routes/users/user.routes.js
  server.js
Labels: review please

#5 Basic student pages and urls
  client/package.json
  client/src/Components/Student.module.css
  client/src/Components/StudentGroup.js
  client/src/Components/StudentMainMenu.js
  client/src/Components/StudentNotification.js
  client/src/Components/StudentProfile.js
  client/src/Components/StudentProject.js
  client/src/Root.js
  client/src/index.js
Labels: ready to merge

#7 Seeders
  migrations/20210330125007-create-preference.js
  models/preference.js
  models/preferencecategory.js
  models/project.js
  seeders/20210412105441-users.js
  seeders/20210413092728-projects.js
  seeders/20210413124851-preferncecategories.js
  seeders/20210415070048-projectrequirements.js
  seeders/20210415074949-preferences.js
  seeders/20210415082523-preferenceselections.js
  seeders/20210415095010-groups.js
Labels: ready to merge

#9 Adding the nodemon dependency
  package-lock.json
  package.json
Labels: ready to merge

#10 Update README.md
  README.md
Labels: review please

#11 Admin authentication middleware
  controllers/projects/projects.controller.js
  controllers/users/users.controller.js
  middleware/admin_auth.js
  middleware/auth.js
  models/group.js
  models/preference.js
  models/preferencecategory.js
  models/preferenceselection.js
  models/project.js
  models/projectrequirement.js
  models/user.js
  package.json
  routes/projects/project.routes.js
  routes/users/projects/project.routes.js
  seeders/20210412105441-users.js
  seeders/20210413092728-projects.js
  seeders/20210413124851-preferncecategories.js
  seeders/20210415070048-projectrequirements.js
  seeders/20210415074949-preferences.js
  server.js
Labels: review please

#14 Auth/Sessions/Routing
  README.md
  controllers/admin/groups/groups.controller.js
  controllers/admin/projects/projects.controller.js
  controllers/admin/users/users.controller.js
  controllers/auth/auth.controller.js
  controllers/projects/projects.controller.js
  controllers/student/groups/groups.controller.js
  controllers/student/profile/profile.controller.js
  controllers/student/projects/projects.controller.js
  controllers/users/projects/projects.controller.js
  controllers/users/users.controller.js
  middleware/admin_auth.js
  models/group.js
  models/groupallocation.js
  models/user.js
  package.json
  routes/admin/groups/groups.routes.js
  routes/admin/projects/projects.routes.js
  routes/admin/users/users.routes.js
  routes/auth/auth.routes.js
  routes/projects/project.routes.js
  routes/student/groups/groups.routes.js
  routes/student/profile/profile.routes.js
  routes/student/projects/projects.routes.js
  routes/users/projects/project.routes.js
  routes/users/user.routes.js
  seeders/20210412105441-users.js
  seeders/20210415074949-preferences.js
  seeders/20210415082523-preferenceselections.js
  seeders/20210415095010-groups.js
  seeders/20210426141502-Group_Allocation.js
  server.js
Labels: feedback addressed
